server:
  port: 7010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=X-Powered-By, Vadiraja
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Powered-By, Vadiraja
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/music/**
          filters:
            - AddResponseHeader=X-Powered-By, Vadiraja
        - id: messaging-route
          uri: lb://messaging-service
          predicates:
            - Path=/messaging/**
          filters:
            - AddResponseHeader=X-Powered-By, Vadiraja
        - id: task-scheduler-route
          uri: lb://task-scheduler-service
          predicates:
            - Path=/task-sch
              - AddResponseHeader=X-Powered-By, Vadiraja

            # Add services hereeduler/**
          filters:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
